name: Build Portable Electron App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Package portable exe
        run: npx electron-builder --win portable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-exe
          path: dist/*.exe
